  - Promise的作用和简单用法
    介绍：
    1. Promise 新建后就会立即执行(重要 经常结合考事件轮询)
    2. then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）then方法里面返回的值(return)被作为下一个then函数里面的参数被接收到
    3. .then()方法可以接收两个参数，两个回调，第一个回调里面的参数是resolve抛出的，第二个回调里面的参数是reject抛出的。第二个参数也和.catch()是一样的
    4. Promise.prototype.catch方法是.then(null, rejection)或.then(undefined, rejection)的别名，用于指定发生错误时的回调函数。另外，then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获。
    5. 一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。
    6. 可以发现reject方法的作用，等同于抛出错误。
    7. 如果 Promise 状态已经变成resolved，再抛出错误是无效的。Promise 在resolve语句后面，再抛出错误，不会被捕获，等于没有抛出。因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了。(重要)
    8. Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。
    9. Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”，只会影响Promise自己的代码执行，不会影响到其他代码的执行
    10. then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法，前一个then方法里return的值作为参数传入下一个回调函数中 可以在下一个回调函数的参数中拿到
    11. catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法。
    12. resolve函数的参数除了正常的值以外，还可能是另一个 Promise 实例
    13. Promise.prototype.finally()方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。finally方法的回调函数不接受任何参数，这意味着finally方法里面的操作与状态无关，是不依赖Promise执行结果的 finally方法本质上是then方法的特例。finally方法总是会返回原来的值
    ```js finally方法的实现
    Promise.prototype.finally = function (callback) {
      let P = this.constructor;
      return this.then(
        value  => P.resolve(callback()).then(() => value),
        reason => P.resolve(callback()).then(() => { throw reason })
      );
    };
    ```
    14. Promise.all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例(返回值也是Promise 可以在then中拿到返回的结果)。
    ```js
    const p = Promise.all([p1, p2, p3])
    ```
    注意，如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
    接受一个数组作为参数，p1、p2、p3都是 Promise 实例，如果不是，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理。另外，Promise.all()方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例
    > 只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
    > 只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数。
    15. Promise.race()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例
    ```js
    const p = Promise.race([p1, p2, p3])
    ```
    只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给p的回调函数。
    16. Promise.allSettled()
    - 方法接受一组 Promise 实例作为参数，包装成一个新的 Promise 实例。只有等到所有这些参数实例都返回结果，不管是fulfilled还是rejected，包装实例才会结束。(这个方法能保证所有的请求都执行完毕 而不像race和all方法一样可能导致有请求没有发出)
    - 该方法返回的新的 Promise 实例，一旦结束，状态总是fulfilled，不会变成rejected。状态变成fulfilled后，Promise 的监听函数接收到的参数是一个数组，每个成员对应一个传入Promise.allSettled()的 Promise 实例。
    - Promise.allSettled()的返回值状态只可能变成fulfilled，在then方法的回调里面接收到的是一个数组.该数组的每个成员都是一个对象，对应传入    Promise.allSettled()的两个 Promise 实例。每个对象都有status属性，该属性的值只可能是字符串fulfilled或字符串rejected。fulfilled时，对象有value属性，rejected时有reason属性，对应两种状态的返回值。如下
    ```js
    [
      { status: 'fulfilled', value: 42 },
      { status: 'rejected', reason: -1 }
    ]
    ```
    17. Promise.any()
    - 只要参数实例有一个变成fulfilled状态，包装实例就会变成fulfilled状态；如果所有参数实例都变成rejected状态，包装实例就会变成rejected状态。
      Promise.any()跟Promise.race()方法很像，只有一点不同，就是不会因为某个 Promise 变成rejected状态而结束
      Promise.any()抛出的错误，不是一个一般的错误，而是一个 AggregateError 实例。它相当于一个数组，每个成员对应一个被rejected的操作所抛出的错误。相当于是一个包含所有错误的数组一样
    18. Promise.resolve() 将一个对象转化为Promise风格的对象 返回一个立即resolve的Promise
    > Promise.resolve方法的参数分成四种情况。
      1. 参数是一个 Promise 实例
      如果参数是 Promise 实例，那么Promise.resolve将不做任何修改、原封不动地返回这个实例。
      2. 参数是一个thenable对象
      thenable对象指的是具有then方法的对象,Promise.resolve方法会将这个对象转为 Promise 对象，然后就立即执行thenable对象的then方法
      3. 参数不是具有then方法的对象，或根本就不是对象
      如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的 Promise 对象，状态为resolved。
      4. 不带有任何参数
      Promise.resolve()方法允许调用时不带参数，直接返回一个resolved状态的 Promise 对象。
      所以，如果希望得到一个 Promise 对象，比较方便的方法就是直接调用Promise.resolve()方法。
      * 需要注意的是，立即resolve()的 Promise 对象，是在本轮“事件循环”（event loop）的结束时执行，而不是在下一轮“事件循环”的开始时。(微任务)
    19. Promise.reject() 返回一个立即 reject的Promise对象, 参数没有多种情况 统一当成是catch回调中的参数被接收到
      * 注意，Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。这一点与Promise.resolve方法不一致。
    20. Promise.try()
      有没有一种方法，让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API 呢？
      有两种写法,第一种写法是用async函数来写。
      ```js
      const f = () => console.log('now');
      (async () => f())();
      console.log('next');
      // now
      // next
      ```
    22. 缺点：
    Promise也有一些缺点。
    1. 首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。
    2. 其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。
    3. 第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。
  - 链式调用
    1. jQuery的链式调用是return this的妙用，即需要链式调用的方法里面 返回一下this就可以实现链式调用
    2. Promise的链式调用是每个then都返回一个promise
  - Promise封装 实现Ajax的操作
    ```js
    const getJSON = function(url) { 
      const promise = new Promise(function(resolve, reject){
        const handler = function() {
          if (this.readyState !== 4) { // 原生XMLHttpRequest()对象含有四个状态码 0 1 2 3 4代表不同含义
            return;
          }
          if (this.status === 200) {
            resolve(this.response);
          } else {
            reject(new Error(this.statusText));
          }
        };
      const client = new XMLHttpRequest();
      client.open("GET", url);
      client.onreadystatechange = handler;
      client.responseType = "json";
      client.setRequestHeader("Accept", "application/json");
      client.send(); // 真正发送请求
      });
      return promise;
    };

    getJSON("/posts.json").then(function(json) {
      console.log('Contents: ' + json);
    }, function(error) {
      console.error('出错了', error);
    });
    ```
  - async函数的作用和用法
    介绍：
      处理异步编程的最新解决方法 - 将异步的操作转化为直观理解的同步顺序。async 关键字是用于表示一个函数里面有异步操作的含义。
    1. 它通过返回一个 Promise 对象来返回结果。它的最大的特点是：通过 async / await 将异步的操作转为同步，但是写法和结构却是和我们平时写的（同步代码）是一样
    2. co 模块约定，yield 命令后面只能是 Thunk 函数或 Promise对象。而 async 函数的 await 命令后面则可以是 Promise 或者 原始类型的值（Number，string，boolean，但这时等同于同步操作）。如果不是 Promise对象 就会返回其对应的值。
    3. 返回值是 Promise。async 函数返回值是 Promise 对象，比 Generator 函数返回的 Iterator 对象方便，可以直接使用 then() 方法进行调用 async 函数内部 return 返回的值。会成为 then 方法回调函数的参数。
    4. 如果 async 函数内部抛出异常，则会导致返回的 Promise 对象状态变为 reject 状态。抛出的错误而会被 catch 方法回调函数接收到。

    ### 来重新整理一下async/await的用法
    1. async函数表明一个函数里面有异步的操作 是Generator的语法糖 更加语义化的解决了回调地狱 以及Generator执行需要执行器(async自带执行器)
    2. async函数返回一个Promise对象来返回函数内部的结果(执行完async函数就会自动返回一个Promise对象 函数里面的返回值只是作为Promise.then()的回     调被接收而已) 函数内部返回值return作为Promise.then()方法中的参数被接收到 如果async函数内部抛出异常      
        如：throw new Error('error') 会在 Promise.catch()的方法参数中被接受到 await后面的Promise如果出错的话 没设置try/catch时可以在Primose.catch()的回调中的参数接收到 如果设置了try/catch 则在catch的参数中被接受到
   
    3. async函数返回的Promise对象 必须等到其中内部的await 操作全部结束之后 返回的Promise对象 状态才会发生改变。也就是说，必须要等到async函数内     部的所有await 执行完毕之后 Promise.then()方法的回调才能被调用
    4. 正常情况下，await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。
    5. async 函数的语法不难，难在错误处理上 如果你在一个async函数中放置多个await函数的话 如果其中有一个await为reject状态 后面的await就都不会执行了。
      解决方法：添加try/catch 将所有的await操作都放置在try中(可能发生错误的的代码) catch中放置对错误处理的代码
      > 补充：try/catch语法
        try/catch javascript中常见处理异常的一种标准方式
        ##### 处理未知的错误时使用到 try/catch 比如引用一些三方库中的函数时
        ```js
        try {

        } catch(error) {

        } finally {
          
        }
        ```
        1. try中任何代码发生了错误 就会立即退出代码执行过程 然后接着执行catch
        2. catch块可以接收到一个包含错误信息的对象 通过catch函数的参数获取 各个浏览器都有一个保存错误的共同message属性
        3. finally子句 无论在任何情况下都会执行 只要finally子句中存在return try/catch中的return都会被忽略(所以慎用finally子句) 存在finally   catch变为可选的存在
      > 补充：抛出错误的知识
        1. 有7种错误类型：
          - Error(基类 其他6种错误都继承自该类 一般是开发人员自己定义的错误 或则浏览器抛出的)
          - EvalError(使用eval()函数而发生异常的时候被抛出:没有把eval()当成函数调用就会抛出错误)
          - RangeError(数值超出相应的范围触发)
          - ReferenceError(找不到对象的时候触发 较为常见 如找不到该变量)
          - SynataxError(把错误的语法传入eval()函数中)
          - TypeError(执行特定于类型的操作时 变量的类型不符合要求所致 如 new操作 等)
          - URIError(在使用encodeURI()或者decodeURI() 而URI格式不正确的时候)
        2. throw操作符 抛出自定义错误 后面跟一个值 这个值是什么类型 没有要求
          - 一般用法： throw new Error('error')
          - 在遇到throw操作符的时候 代码会立即停止执行 仅当有try/catch语句捕获到被抛出的值时,代码才会继续执行
  - class的语法和简单用法
    > class的基本语法介绍：
    - 类的数据类型就是函数，类本身就指向构造函数，
    - 类的所有方法都定义在类的prototype属性上面。
    - Object.assign方法可以很方便地一次向类添加多个方法 
      * Object.assign(className.prototype, {
          toString(){},
          toValue(){}
        })
    - 类的内部所有定义的方法，都是不可枚举的(与 ES5 的行为不一致)
    - 类必须使用new调用，否则会报错(它跟普通构造函数的一个主要区别)
    - 实例的属性除非显式定义在其本身（即定义在this对象上），否则都是定义在原型上（即定义在class上）
    - 类的所有实例共享一个原型对象。
    - 可以通过实例的__proto__属性为“类”添加方法 __proto__ 并不是语言本身的特性，这是各大厂商具体实现时添加的私有属性，虽然目前很多现代浏览器的 JS 引擎中都提供了这个私有属性，但依旧不建议在生产中使用该属性，避免对环境产生依赖。生产环境中，我们可以使用 Object.getPrototypeOf 方法来获取实例对象的原型，然后再来为原型添加方法/属性。
    > class的继承
      - Class 可以通过extends关键字实现继承，这比 ES5 的通过修改原型链实现继承，要清晰和方便很多
      - constructor方法和toString方法之中，都出现了super关键字，它在这里表示父类的构造函数，用来新建父类的this对象。
        1. 写在constructor里面：super(x, y); // 表示调用父类的constructor(x, y)方法
        2. 写在方法里面：return this.color + ' ' + super.toString(); // 表示调用父类的toString()方法
      - 子类必须在constructor方法中调用super方法，否则新建实例时会报错。(这里会报ReferenceError的错误) 不写constructor方法会默认添加
      - * (重要)ES5 的继承，实质是先创造子类的实例对象this，然后再将父类的方法添加到this上面（Parent.apply(this)）。ES6 的继承机制完全不同，实质是先将父类实例对象的属性和方法，加到this上面（所以必须先调用super方法），然后再用子类的构造函数修改this。
  - 前端打包工具的了解grunt、gulp、webpack、rollup